_wandb:
    value:
        cli_version: 0.21.1
        e:
            uljg2kbegmd3ealnhmsv82an6kdcsjh4:
                args:
                    - --app
                    - my-first-app
                    - --num-supernodes
                    - "10"
                    - --backend-config
                    - '{"client-resources": {"num-cpus": 1, "num-gpus": 0.25}}'
                    - --run-config
                    - num-server-rounds=5
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "397562048512"
                email: mail2shahg@gmail.com
                executable: /home/syed/miniconda3/envs/flwr/bin/python3.10
                git:
                    commit: 5e12e9783829d776de4f6b8093b1ae4020e82b10
                    remote: https://github.com/SohaibAShah/Flower-Tutorials.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-90cc744d-4b09-d5cd-25bc-1cdd32a36c95
                host: TUF
                memory:
                    total: "24603979776"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/syed/miniconda3/envs/flwr/bin/flower-simulation
                python: CPython 3.10.0
                root: /home/syed/PhD/Flower-Tutorials
                startedAt: "2025-08-16T04:43:49.486278Z"
                writerId: uljg2kbegmd3ealnhmsv82an6kdcsjh4
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
                - 61
            "4": 3.10.0
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
